export { default as Main } from '../src/layouts/Main.jsx';
export { default as Login } from '../src/pages/Login.jsx';
export { default as Register } from '../src/pages/Register.jsx';
export { default as ProductDetail } from '../src/pages/ProductDetail.jsx';
export { default as Tv } from '../src/pages/Tv.jsx';
export { default as Phones } from '../src/pages/Phones.jsx';
export { default as Speakers } from '../src/pages/Speakers.jsx';
export { default as Air } from '../src/pages/Air.jsx';
export { default as Fridge } from '../src/pages/Fridge.jsx';
